version: '3.8'

services:
  brave-search:
    image: mcp/brave-search
    env_file: .env.brave
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
    environment:
      - ENCRYPT_CONFIG=true

  github:
    image: mcp/github
    env_file: .env.github
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
    environment:
      - ENCRYPT_CONFIG=true
